# if u installed prometheus with helm u should run this command after the install: 
# helm upgrade <release-name> prometheus-community/prometheus --values prometheus-values.yaml
scrape_configs:
  - job_name: myapp
    metrics_path: / # this is my application endpoint what prometheus watches
    static_configs:
      - targets: ['myapp-service:80']
